name: test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  awesome_dialog: ^3.2.1
  carousel_slider: ^5.0.0
  country_picker: ^2.0.21
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  flutter:
    sdk: flutter
  flutter_credit_card: ^4.1.0
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.1
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.17
  font_awesome_flutter: ^10.8.0
  get: ^4.7.2
  go_router: ^14.8.0
  google_fonts: ^6.2.1
  http: ^1.4.0
  icons_flutter: ^0.0.5
  image_picker: ^1.1.2
  intl: ^0.20.2
  intl_phone_field: ^3.2.0
  line_awesome_flutter: ^3.0.1
  pretty_qr_code: ^3.4.0
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  smooth_page_indicator: ^1.2.1
  theme_provider: ^0.6.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    #   - images/a_dot_ham.jpeg
    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/to/resolution-aware-images
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/to/asset-from-package
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
    # fonts:
    # - family: Lora
    # fonts:
    # - asset: assets/fonts/Lora-Italic-VariableFont_wght.ttf
    # - asset: assets/fonts/Lora-VariableFont_wght.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
